import {NextPage} from "next";
import styles from "../../styles/Home.module.css";
import Head from "next/head";
import {set1} from "../questions";

export interface Answer {
    id: number
    desc: string
}

export interface Rationale {
    id: number
    desc: string
}

export interface Question {
    id: number
    question: string
    answers: Answer[]
    answerId: number[]
    rationale: Rationale[]
}

export const getServerSideProps = async () => {

    return {
        props: { set1 }, // will be passed to the page component as props
    }
}

const Quiz: NextPage = (data) => {
    const questions: Question[] = (data as any).set1 as Question[]
    console.log(JSON.stringify(questions))
    return (
        <div className={styles.container}>
            <Head>
                <title>Learn!</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                Quiz!
            </main>
        </div>
    )
}

export default Quiz